#!/usr/bin/env bash

source ./lib/tui.sh || exit 1
source ./lib/raintracker.sh || exit 1
source ./lib/math.sh || exit 1
source ./lib/variables.sh || exit 1

trap cleanup exit
trap 'echo resize >&3' SIGWINCH

setup
event_handler
